### ISSUE TITLE
Problems with width of page

### ISSUE THREAD

**Issue by ellieschieder** [rei/rei-cedar#155] opened 2023-11-18 17:59 UTC
Hey there,
thank you for the design system.

I noticed that on my MacBook Pro m1 in firefox, the pages is a bit broken. If I can assist further in debugging, let me know.

![Screenshot 2023-11-18 at 18-57-45 Cedar Design System REI Co-op](https://github.com/rei/rei-cedar/assets/102893018/233b95d0-6ae3-4898-a9cb-4d4051bb3a00)
![Screenshot 2023-11-18 at 18-54-31 Cedar Design System REI Co-op](https://github.com/rei/rei-cedar/assets/102893018/d8b2943f-a86c-4acd-8398-0c8adb4b7a88)

**Comment by benjag** [comment] 2023-11-29 20:34
Hi @ellieschieder, thanks for the screenshot. I am unable to reproduce this issue on an M1 macbook pro in any browser. Is it still occurring for you?

**Comment by benjag** [comment] 2023-12-09 20:35
Closing as unreproducible

**Closed as not planned** 2023-12-09 20:35 UTC
Labels: question
